samtools = "/data/home/pengjia/miniconda3/envs/default/bin/samtools"
tabix = "/data/home/pengjia/miniconda3/envs/default/bin/tabix"
picard = "/data/home/pengjia//miniconda3/envs/default/bin/picard"
bcftools = "/data/home/pengjia/miniconda3/envs/default/bin/bcftools"
bcftools_plot = "/data//home/pengjia/miniconda3/envs/default/bin/plot-vcfstats"
whatshap = "/data/home/pengjia/miniconda3/envs/default/bin/whatshap"

minimap2 = "/data/home/pengjia/miniconda3/envs/default/bin/minimap2"
pbmm2 = "/data/home/pengjia/miniconda3/envs/default/bin/pbmm2"
ngmlr = "/data/home/pengjia/miniconda3/envs/default/bin/ngmlr"

mosdepth = "/data/home/pengjia/miniconda3/envs/default/bin/mosdepth"
qualimap = "/data/home/pengjia/miniconda3/envs/default/bin/qualimap"
fastqc = "/data/home/pengjia/miniconda3/envs/default/bin/fastqc"
multiqc = "/data/home/pengjia/miniconda3/envs/default/bin/multiqc"
discvrseq="/data/home/pengjia/mysoftware/DISCVRSeq-1.25.jar"


cuteSV = "/data/home/pengjia/miniconda3/envs/default/bin/cuteSV"
varscan = "/data/home/pengjia/miniconda3/envs/ngs/bin/varscan"
sniffles = "/data/home/pengjia/miniconda3/envs/default/bin/sniffles"
pbsv = "/data/home/pengjia/miniconda3/envs/default/bin/pbsv"
SURVIVOR = "/data/home/pengjia/miniconda3/envs/default/bin/SURVIVOR"
bgzip = "/data/home/pengjia/miniconda3/envs/default/bin/bgzip"
SVision="/data/home/pengjia/miniconda3/envs/svisionenv/bin/SVision"


gatk = "/home/pengjia/miniconda3/envs/ngs/bin/gatk"
vep_data = "/home/pengjia/mysoftware/annotation.smk/vep_data"
discvrseq = "/home/pengjia/mysoftware/DISCVRSeq/DISCVRSeq-1.25.jar"

#
# pbmm2 = "/home/pengjia/miniconda3/envs/ngs/bin/pbmm2"
# ngmlr = "/home/pengjia/miniconda3/envs/ngs/bin/ngmlr"
# picard = "/home/pengjia/miniconda3/envs/ngs/bin/picard"
# vep_data = "/home/pengjia/mysoftware/annotation.smk/vep_data"
# bcftools = "/home/pengjia/miniconda3/envs/default/bin/bcftools"
# bcftools_plot = "/home/pengjia/miniconda3/envs/default/bin/plot-vcfstats"
# samtools = "/home/pengjia/miniconda3/envs/default/bin/samtools"
# tabix = "/home/pengjia/miniconda3/envs/default/bin/tabix"
# whatshap = "/home/pengjia/miniconda3/envs/default/bin/whatshap"
# discvrseq = "/home/pengjia/mysoftware/DISCVRSeq/DISCVRSeq-1.25.jar"
# mosdepth = "/home/pengjia/miniconda3/envs/ngs/bin/mosdepth"
# qualimap = "/home/pengjia/miniconda3/envs/ngs/bin/qualimap"
# gatk = "/home/pengjia/miniconda3/envs/ngs/bin/gatk"
# varscan = "/home/pengjia/miniconda3/envs/ngs/bin/varscan"
# fastqc = "/home/pengjia/miniconda3/envs/ngs/bin/fastqc"
# multiqc = "/home/pengjia/miniconda3/envs/ngs/bin/multiqc"
# qualimap = "/home/pengjia/miniconda3/envs/ngs/bin/qualimap"
# cuteSV = "/home/pengjia/miniconda3/envs/SVLR/bin/cuteSV"
